### PR TITLE
Ignore PyCharm project files

### PR DESCRIPTION
**Pull request by johnthagen**
Ignore PyCharm project files from contributors using PyCharm.

### CODE REVIEW

**Comment by jszakmeister** [comment]
Shouldn't editor-based artifacts be in your global ignores?  In Git, you can put them into `$XDG_CONFIG_HOME/git/ignore` or `$HOME/.config/git/ignore`, if `XDG_CONFIG_HOME` is not defined.  See "core.excludesFile" in the [gitconfig man page](https://git-scm.com/docs/git-config), or the [gitignore man page](https://git-scm.com/docs/gitignore) for more information (not that there's much more to be said!). :-)

**Comment by johnthagen** [comment]
Thanks for the references!

Unfortunately, I cannot globally ignore IntelliJ IDEA based project files because in some projects that I contribute to, such as [`intellij-rust`](https://github.com/intellij-rust/intellij-rust), the IntelliJ project files are actually significant.

**Comment by jszakmeister** [comment]
You can add it to .git/info/exclude instead, as mentioned in the
documentation.  I use it all the time for situations exactly like this. :-)

-John

**Comment by drmikehenry** [comment]
I didn't realize that .git/info/exclude was available as an alternative to global ignores and checked-in .gitignore files.  This seems like a good way to address the problem, plus I got to learn something, too :-)

**Pull request closed without merging**
